<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishReferencedProjects>false</PublishReferencedProjects>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MichaelKim.Hello.v2.ServiceDefaults\MichaelKim.Hello.v2.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" Version="9.5.2" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
  </ItemGroup>

</Project>
