name: Build and deploy ASP.Net Core app to Azure Web App - hello-v2-backend-apiservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.100'

      - name: Restore dependencies
        run: dotnet restore ./MichaelKim.Hello.v2.ApiService/MichaelKim.Hello.v2.ApiService.csproj

      - name: Build
        run: dotnet build ./MichaelKim.Hello.v2.ApiService/MichaelKim.Hello.v2.ApiService.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./MichaelKim.Hello.v2.ApiService/MichaelKim.Hello.v2.ApiService.csproj -c Release -o ./publish --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A88795F8641343FDB57C90E6D69D0850 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E14CC3CBC6F14D6FBA841586D4B58C43 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F230DCFCECC642D3BF06F473DD4366D1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hello-v2-backend-apiservice'
          slot-name: 'Production'
          package: .

